
language: rust

rust:
  - 1.39.0
  - 1.40.0
  - 1.41.0
  - 1.41.1
  - stable
  - beta
  - nightly

services:
  - "docker"

matrix:
  allow_failures:
    - rust: nightly
    - env: ALLOW_FAILURE=TRUE

  include:
    # Rustfmt
    - stage: format
      name: "Format"
      rust: stable
      install:
        - rustup component add rustfmt-preview
      before_script:
        - cargo fmt --version
      script:
        - cargo fmt -- --check

    # Clippy
    - stage: clippy
      name: "Clippy"
      rust: stable
      install:
        - rustup component add clippy-preview
      script:
        # Fail if clippy output contains "error:" or "warning:"
        - cargo clippy 2>&1 | tee ./clippy.out && ! grep -qe  "error:\|warning:" ./clippy.out

    - stage: "test"
      name: "Unit Tests"
      rust: stable
      script: cargo test

    - stage: version
      name: "Check version"
      script: make docker-registry-login && make check-version

    - stage: deploy
      name: "Deploy to docker hub"
      script: make docker-registry-login && \
              make docker-build && \
              make docker-push-registry
      if: branch = master

cache:
  cargo: true
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

stages:
  - version
  - format
  - clippy
  - test
  - deploy

addons:
  apt:
    packages:
      - libssl-dev      # Required for tarpaulin
      - make
    update: true