
language: rust

rust:
  - 1.39.0
  - 1.40.0
  - 1.41.0
  - 1.41.1
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
    - env: ALLOW_FAILURE=TRUE

  include:
    # Rustfmt
    - rust: stable
      install:
        - rustup component add rustfmt-preview
      before_script:
        - cargo fmt --version
      script:
        - cargo fmt -- --check

    # Clippy
    - rust: stable
      install:
        - rustup component add clippy-preview
      script:
        # Fail if clippy output contains "error:" or "warning:"
        - cargo clippy 2>&1 | tee ./clippy.out && ! grep -qe  "error:\|warning:" ./clippy.out

before_install:
  - sudo apt-get -y install gcc make autotools-dev jq
env:
  jobs:
    - JQ_LIB_DIR=/usr/bin/jq
script:
  - cargo test
cache:
  cargo: true
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

addons:
  apt:
    packages:
      - libssl-dev  # Required for tarpaulin
    update: true