[package]
name = "rs_json_transform_worker"
version = "0.1.0"
authors = ["Mathia Haure-Touze <mathia.haure-touzet.ext@francetv.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
